/* ============================================================
   placement-sheets.js — reference sheets & code templates
   Sheet: { key, name, side, tagline, blocks[] }
   Block kinds:
     {t:"p",   text}                        paragraph (supports `code`)
     {t:"h",   text}                        sub-heading
     {t:"list",items:[]}                    bulleted list (supports `code`)
     {t:"table",head:[], rows:[[]]}         table (supports `code` in cells)
     {t:"code",title, lang, lines:[]}       code block (rendered verbatim)
   ============================================================ */

var SHEETS = [
{
  key:"complexity", name:"Complexity Reference", side:"dsa",
  tagline:"The table you should be able to reproduce on a whiteboard.",
  blocks:[
    {t:"h",text:"Operations by data structure (average / worst)"},
    {t:"table",
     head:["Structure","Access","Search","Insert","Delete","Space"],
     rows:[
      ["Array (static)","O(1)","O(n)","O(n)","O(n)","O(n)"],
      ["Dynamic array","O(1)","O(n)","O(1) amortised","O(n)","O(n)"],
      ["Singly linked list","O(n)","O(n)","O(1) at head","O(1) with prev ref","O(n)"],
      ["Hash map","—","O(1) / O(n)","O(1) / O(n)","O(1) / O(n)","O(n)"],
      ["Balanced BST","O(log n)","O(log n)","O(log n)","O(log n)","O(n)"],
      ["Binary heap","O(1) peek","O(n)","O(log n)","O(log n) extract","O(n)"],
      ["Trie","—","O(L)","O(L)","O(L)","O(chars x alphabet)"],
      ["Union-Find","—","O(alpha(n))","O(alpha(n))","—","O(n)"],
      ["Segment tree","—","O(log n)","O(log n)","O(log n)","O(4n)"],
      ["Deque","O(1) ends","O(n)","O(1) ends","O(1) ends","O(n)"]
     ]},
    {t:"h",text:"Sorting algorithms"},
    {t:"table",
     head:["Algorithm","Best","Average","Worst","Space","Stable"],
     rows:[
      ["Merge sort","O(n log n)","O(n log n)","O(n log n)","O(n)","Yes"],
      ["Quicksort","O(n log n)","O(n log n)","O(n^2)","O(log n)","No"],
      ["Heapsort","O(n log n)","O(n log n)","O(n log n)","O(1)","No"],
      ["Insertion sort","O(n)","O(n^2)","O(n^2)","O(1)","Yes"],
      ["Counting sort","O(n + k)","O(n + k)","O(n + k)","O(k)","Yes"],
      ["Radix sort","O(d(n + k))","O(d(n + k))","O(d(n + k))","O(n + k)","Yes"],
      ["Quickselect","O(n)","O(n)","O(n^2)","O(1)","No"]
     ]},
    {t:"h",text:"Graph algorithms"},
    {t:"table",
     head:["Algorithm","Time","Handles","Use when"],
     rows:[
      ["BFS","O(V + E)","Unweighted","Shortest hops, level order, multi-source spread"],
      ["DFS","O(V + E)","Any","Components, cycles, topological order, path enumeration"],
      ["Dijkstra","O((V+E) log V)","Non-negative weights","Cheapest path with costs"],
      ["Bellman-Ford","O(V x E)","Negative weights","Negative edges, or 'at most K edges'"],
      ["Floyd-Warshall","O(V^3)","Negative weights","All-pairs, small V (under ~400)"],
      ["Kahn topo sort","O(V + E)","DAG only","Ordering with prerequisites; detects cycles"],
      ["Kruskal MST","O(E log E)","Undirected","Sparse graphs, edge list given"],
      ["Prim MST","O(E log V)","Undirected","Dense graphs, adjacency given"]
     ]},
    {t:"h",text:"Reverse-engineering the intended solution from n"},
    {t:"table",
     head:["Constraint on n","Budget suggests","Likely technique"],
     rows:[
      ["n <= 10","O(n!) or O(2^n * n)","Full permutation search, brute force"],
      ["n <= 20","O(2^n)","Bitmask DP, subset enumeration, meet in the middle"],
      ["n <= 100","O(n^4)","Interval DP, heavy nested loops"],
      ["n <= 500","O(n^3)","Floyd-Warshall, matrix chain, some DP"],
      ["n <= 5,000","O(n^2)","2-D DP, pairwise scans"],
      ["n <= 10^5","O(n log n)","Sort, heap, binary search, segment tree"],
      ["n <= 10^6","O(n) or O(n log log n)","Hash map single pass, sieve, two pointers"],
      ["n <= 10^9","O(log n) or O(sqrt n)","Binary search the answer, maths, fast power"]
     ]},
    {t:"h",text:"Things people get wrong under pressure"},
    {t:"list",items:[
      "Building a heap is `O(n)`; pushing n items one at a time is `O(n log n)`.",
      "Union-Find is only near-constant with BOTH path compression and union by rank.",
      "Recursion costs `O(depth)` stack — state it separately from auxiliary space.",
      "Amortised is a worst-case sequence guarantee; average is a probabilistic one.",
      "Say `O(1)` AUXILIARY space when the output itself is `O(n)`."
    ]}
  ]
},
{
  key:"patterns", name:"Signal to Technique Map", side:"dsa",
  tagline:"Read the problem statement, find the row, write the code.",
  blocks:[
    {t:"p",text:"Interview problems are written to disguise a small set of techniques. Train the mapping, not the problems."},
    {t:"table",
     head:["What the problem says","What it means","Reach for"],
     rows:[
      ["Contiguous subarray, all positive","Window is monotone","Sliding window"],
      ["Count subarrays summing to K, negatives allowed","Window is NOT monotone","Prefix sum + hash map"],
      ["Sorted array, find a pair","Monotone from both ends","Two pointers"],
      ["Minimise the maximum / maximise the minimum","Feasibility is monotone","Binary search on the answer"],
      ["Next greater / previous smaller / span","Amortised push-pop","Monotonic stack"],
      ["Top K / Kth largest / K closest","Only the extreme matters","Size-K heap, or bucket sort"],
      ["Median of a stream","Two ordered halves","Two heaps"],
      ["All arrangements / all valid boards","Exponential enumeration","Backtracking + pruning"],
      ["Number of ways / min cost, overlapping subproblems","Optimal substructure","Dynamic programming"],
      ["Prerequisites, build order, dependencies","DAG ordering","Topological sort (Kahn)"],
      ["Are these two connected, repeatedly","Dynamic connectivity","Union-Find"],
      ["Shortest path, all edges equal","Uniform cost","BFS"],
      ["Shortest path, weighted non-negative","Greedy frontier","Dijkstra"],
      ["Shortest path, negative edges or K stops","Layered relaxation","Bellman-Ford"],
      ["Spread from many sources at once","Simultaneous frontier","Multi-source BFS"],
      ["Prefix / autocomplete / dictionary match","Shared prefixes","Trie"],
      ["Appears once, everything else twice","Self-cancelling","XOR"],
      ["Merge overlapping intervals","Order by where they start","Sort by START, sweep"],
      ["Maximum non-overlapping intervals","Earliest finish is safest","Sort by END, greedy"],
      ["Two strings compared as subsequences","2-D prefix state","2-D DP (LCS / edit distance)"],
      ["Palindromic substrings","Symmetry around a centre","Expand around centre"],
      ["Values are 1..n inside an array of length n","Index is a free hash","Index-as-hash (negate or swap)"],
      ["Longest streak of consecutive things","Runs share an offset","Gaps and islands"],
      ["Maximum of every window of size k","Discard dominated elements","Monotonic deque"],
      ["Pick items under a capacity","Take or skip per item","Knapsack DP"],
      ["Cycle in a linked list","Two speeds meet","Floyd tortoise and hare"],
      ["One pass, constant space","Constrained sweep","Two pointers / Kadane / Boyer-Moore / XOR"]
     ]},
    {t:"h",text:"When two patterns compete"},
    {t:"list",items:[
      "Sliding window vs prefix sum — negatives present? Prefix sum. Otherwise window.",
      "Heap vs sort — do you need all of it ordered, or only the top K? K only means heap.",
      "BFS vs Dijkstra — are all edge weights equal? Then BFS, and say so; the log factor is free marks.",
      "DFS vs Union-Find — is the graph being built incrementally? Union-Find. Static? Either.",
      "Greedy vs DP — can you prove an exchange argument? If not, assume DP.",
      "Backtracking vs DP — do they want every solution, or just the count/best? Every solution means backtracking."
    ]}
  ]
},
{
  key:"templates", name:"Code Templates", side:"dsa",
  tagline:"Write these from memory. Under pressure you will not invent them.",
  blocks:[
    {t:"p",text:"Python is used here for brevity. The point is the SHAPE — memorise the invariant, not the syntax."},
    {t:"code",title:"Binary search — lower bound (the only template you need)",lang:"python",lines:[
      "def lower_bound(a, target):",
      "    lo, hi = 0, len(a)          # hi is EXCLUSIVE",
      "    while lo < hi:",
      "        mid = lo + (hi - lo) // 2",
      "        if a[mid] < target:     # predicate is False here",
      "            lo = mid + 1",
      "        else:                   # predicate is True here",
      "            hi = mid",
      "    return lo                   # first index where a[i] >= target",
      "",
      "# Binary search on the ANSWER — same shape, different predicate",
      "def min_feasible(lo, hi, ok):",
      "    while lo < hi:",
      "        mid = lo + (hi - lo) // 2",
      "        if ok(mid): hi = mid",
      "        else:       lo = mid + 1",
      "    return lo"
    ]},
    {t:"code",title:"Sliding window — variable size",lang:"python",lines:[
      "from collections import defaultdict",
      "",
      "def longest_valid(s):",
      "    count = defaultdict(int)",
      "    left = 0",
      "    best = 0",
      "    for right, ch in enumerate(s):",
      "        count[ch] += 1",
      "        while not valid(count):          # shrink until the window is legal",
      "            count[s[left]] -= 1",
      "            if count[s[left]] == 0:",
      "                del count[s[left]]       # keep len(count) meaningful",
      "            left += 1",
      "        best = max(best, right - left + 1)   # LONGEST: record after expanding",
      "    return best",
      "",
      "# SHORTEST valid window: record INSIDE the shrink loop instead,",
      "# while the window is still valid."
    ]},
    {t:"code",title:"Prefix sum + hash map — count subarrays summing to K",lang:"python",lines:[
      "from collections import defaultdict",
      "",
      "def subarrays_with_sum(nums, k):",
      "    seen = defaultdict(int)",
      "    seen[0] = 1              # the empty prefix — forgetting this is the classic bug",
      "    total = 0",
      "    running = 0",
      "    for x in nums:",
      "        running += x",
      "        total += seen[running - k]",
      "        seen[running] += 1",
      "    return total"
    ]},
    {t:"code",title:"Monotonic stack — next greater element",lang:"python",lines:[
      "def next_greater(nums):",
      "    res = [-1] * len(nums)",
      "    stack = []                       # holds INDICES, decreasing by value",
      "    for i, x in enumerate(nums):",
      "        while stack and nums[stack[-1]] < x:",
      "            res[stack.pop()] = x",
      "        stack.append(i)",
      "    return res                       # anything left in the stack has no greater element"
    ]},
    {t:"code",title:"Grid BFS — multi-source, shortest hops",lang:"python",lines:[
      "from collections import deque",
      "",
      "def bfs(grid, sources):",
      "    R, C = len(grid), len(grid[0])",
      "    q = deque(sources)",
      "    seen = set(sources)              # mark on ENQUEUE, never on dequeue",
      "    steps = 0",
      "    while q:",
      "        for _ in range(len(q)):      # one full level per outer iteration",
      "            r, c = q.popleft()",
      "            for dr, dc in ((1,0), (-1,0), (0,1), (0,-1)):",
      "                nr, nc = r + dr, c + dc",
      "                if 0 <= nr < R and 0 <= nc < C and (nr,nc) not in seen and grid[nr][nc] != '#':",
      "                    seen.add((nr, nc))",
      "                    q.append((nr, nc))",
      "        steps += 1",
      "    return steps"
    ]},
    {t:"code",title:"Union-Find with both optimisations",lang:"python",lines:[
      "class DSU:",
      "    def __init__(self, n):",
      "        self.p = list(range(n))",
      "        self.rank = [0] * n",
      "        self.count = n               # number of disjoint components",
      "",
      "    def find(self, x):",
      "        while self.p[x] != x:",
      "            self.p[x] = self.p[self.p[x]]    # path halving",
      "            x = self.p[x]",
      "        return x",
      "",
      "    def union(self, a, b):",
      "        ra, rb = self.find(a), self.find(b)",
      "        if ra == rb:",
      "            return False             # already joined => this edge closes a cycle",
      "        if self.rank[ra] < self.rank[rb]:",
      "            ra, rb = rb, ra",
      "        self.p[rb] = ra",
      "        if self.rank[ra] == self.rank[rb]:",
      "            self.rank[ra] += 1",
      "        self.count -= 1",
      "        return True"
    ]},
    {t:"code",title:"Topological sort — Kahn, with cycle detection",lang:"python",lines:[
      "from collections import deque",
      "",
      "def topo(n, edges):",
      "    adj = [[] for _ in range(n)]",
      "    indeg = [0] * n",
      "    for u, v in edges:               # u must come before v",
      "        adj[u].append(v)",
      "        indeg[v] += 1",
      "    q = deque(i for i in range(n) if indeg[i] == 0)",
      "    order = []",
      "    while q:",
      "        u = q.popleft()",
      "        order.append(u)",
      "        for v in adj[u]:",
      "            indeg[v] -= 1",
      "            if indeg[v] == 0:",
      "                q.append(v)",
      "    return order if len(order) == n else []   # short order => cycle"
    ]},
    {t:"code",title:"Dijkstra — with the stale-entry skip",lang:"python",lines:[
      "import heapq",
      "",
      "def dijkstra(n, adj, src):           # adj[u] = list of (v, w)",
      "    dist = [float('inf')] * n",
      "    dist[src] = 0",
      "    pq = [(0, src)]",
      "    while pq:",
      "        d, u = heapq.heappop(pq)",
      "        if d > dist[u]:",
      "            continue                 # stale entry — THIS is the line people forget",
      "        for v, w in adj[u]:",
      "            nd = d + w",
      "            if nd < dist[v]:",
      "                dist[v] = nd",
      "                heapq.heappush(pq, (nd, v))",
      "    return dist"
    ]},
    {t:"code",title:"Backtracking skeleton — with duplicate suppression",lang:"python",lines:[
      "def solve(nums):",
      "    nums.sort()                      # required for the duplicate skip below",
      "    res, path = [], []",
      "",
      "    def bt(start):",
      "        if is_goal(path):",
      "            res.append(path[:])      # COPY, not a reference",
      "            return",
      "        for i in range(start, len(nums)):",
      "            if i > start and nums[i] == nums[i-1]:",
      "                continue             # skip duplicates at the same depth",
      "            if not feasible(nums[i]):",
      "                continue             # prune — this is what is being graded",
      "            path.append(nums[i])",
      "            bt(i + 1)                # i (not i+1) allows reuse of the same element",
      "            path.pop()               # undo",
      "",
      "    bt(0)",
      "    return res"
    ]},
    {t:"code",title:"DP — memo first, then table, then rolling array",lang:"python",lines:[
      "from functools import lru_cache",
      "",
      "# 1. Get it correct top-down.",
      "@lru_cache(maxsize=None)",
      "def f(i, cap):",
      "    if i == n or cap == 0: return 0",
      "    skip = f(i + 1, cap)",
      "    take = val[i] + f(i + 1, cap - wt[i]) if wt[i] <= cap else 0",
      "    return max(skip, take)",
      "",
      "# 2. Then bottom-up, same recurrence.",
      "dp = [[0] * (C + 1) for _ in range(n + 1)]",
      "for i in range(n - 1, -1, -1):",
      "    for c in range(C + 1):",
      "        dp[i][c] = dp[i+1][c]",
      "        if wt[i] <= c:",
      "            dp[i][c] = max(dp[i][c], val[i] + dp[i+1][c - wt[i]])",
      "",
      "# 3. Only then optimise space. 0/1 knapsack needs the capacity loop REVERSED.",
      "dp1 = [0] * (C + 1)",
      "for i in range(n):",
      "    for c in range(C, wt[i] - 1, -1):        # forward instead => unbounded knapsack",
      "        dp1[c] = max(dp1[c], val[i] + dp1[c - wt[i]])"
    ]},
    {t:"code",title:"Trie",lang:"python",lines:[
      "class Trie:",
      "    def __init__(self):",
      "        self.root = {}",
      "",
      "    def insert(self, word):",
      "        node = self.root",
      "        for ch in word:",
      "            node = node.setdefault(ch, {})",
      "        node['$'] = True             # end-of-word marker",
      "",
      "    def search(self, word, prefix_only=False):",
      "        node = self.root",
      "        for ch in word:",
      "            if ch not in node:",
      "                return False",
      "            node = node[ch]",
      "        return True if prefix_only else '$' in node"
    ]},
    {t:"code",title:"Linked list — dummy head and in-place reverse",lang:"python",lines:[
      "def reverse(head):",
      "    prev = None",
      "    while head:",
      "        nxt = head.next          # save BEFORE you overwrite",
      "        head.next = prev",
      "        prev = head",
      "        head = nxt",
      "    return prev",
      "",
      "def merge(a, b):",
      "    dummy = tail = ListNode(0)   # dummy head removes every special case",
      "    while a and b:",
      "        if a.val <= b.val: tail.next, a = a, a.next",
      "        else:              tail.next, b = b, b.next",
      "        tail = tail.next",
      "    tail.next = a or b",
      "    return dummy.next"
    ]},
    {t:"code",title:"Two heaps — running median",lang:"python",lines:[
      "import heapq",
      "",
      "class MedianFinder:",
      "    def __init__(self):",
      "        self.lo = []             # max-heap, negated",
      "        self.hi = []             # min-heap",
      "",
      "    def add(self, x):",
      "        heapq.heappush(self.lo, -x)",
      "        heapq.heappush(self.hi, -heapq.heappop(self.lo))   # move the max across",
      "        if len(self.hi) > len(self.lo):                    # rebalance",
      "            heapq.heappush(self.lo, -heapq.heappop(self.hi))",
      "",
      "    def median(self):",
      "        if len(self.lo) > len(self.hi): return -self.lo[0]",
      "        return (-self.lo[0] + self.hi[0]) / 2"
    ]}
  ]
},
{
  key:"sqlref", name:"SQL Reference", side:"sql",
  tagline:"Clause order, join behaviour, NULL logic — the parts that decide correctness.",
  blocks:[
    {t:"h",text:"Logical execution order (everything follows from this)"},
    {t:"table",
     head:["#","Clause","Consequence"],
     rows:[
      ["1","FROM / JOIN","Row multiplication happens here — this is where wrong totals begin"],
      ["2","WHERE","Cannot see SELECT aliases; cannot use aggregates"],
      ["3","GROUP BY","Collapses rows into groups"],
      ["4","HAVING","Can use aggregates; cannot use window functions"],
      ["5","Window functions","Evaluated after grouping — so you cannot filter them in WHERE"],
      ["6","SELECT","Aliases are created here"],
      ["7","DISTINCT","Applies to the whole select list, not one column"],
      ["8","ORDER BY","CAN use SELECT aliases, because it runs after SELECT"],
      ["9","LIMIT / OFFSET","Meaningless without a deterministic ORDER BY"]
     ]},
    {t:"h",text:"Join behaviour"},
    {t:"table",
     head:["Join","Keeps","Typical use"],
     rows:[
      ["INNER","Only matching pairs","The default relationship traversal"],
      ["LEFT","All left rows, NULLs on the right","'Include customers with no orders'"],
      ["RIGHT","All right rows","Rare — rewrite as LEFT with the tables swapped"],
      ["FULL OUTER","Everything from both sides","Reconciling two snapshots"],
      ["CROSS","Every combination","Generating a calendar x store grid"],
      ["SELF","Table joined to itself","Employee and manager in one table"],
      ["SEMI (`EXISTS`)","Left rows that have >= 1 match, no duplication","'Customers who ordered at least once'"],
      ["ANTI (`NOT EXISTS`)","Left rows with NO match","'Customers who never ordered'"]
     ]},
    {t:"h",text:"NULL truth table"},
    {t:"table",
     head:["Expression","Result","Consequence"],
     rows:[
      ["`NULL = NULL`","NULL","Row is filtered out — use `IS NULL`"],
      ["`TRUE AND NULL`","NULL","Cannot be confirmed"],
      ["`FALSE AND NULL`","FALSE","Already decided"],
      ["`TRUE OR NULL`","TRUE","Already decided"],
      ["`FALSE OR NULL`","NULL","Cannot be confirmed"],
      ["`NOT NULL` (the operator)","NULL","Negation does not rescue you"],
      ["`x NOT IN (1, NULL)`","NULL for every x","Returns zero rows — use `NOT EXISTS`"],
      ["`COUNT(col)` with NULLs","Skips them","Differs from `COUNT(*)`"],
      ["`SUM` / `AVG` with NULLs","Skips them","`AVG` is not `SUM / COUNT(*)`"],
      ["`'a' || NULL`","NULL","Concatenation is poisoned — wrap in `COALESCE`"]
     ]},
    {t:"h",text:"Aggregate quick rules"},
    {t:"list",items:[
      "`COUNT(*)` counts rows. `COUNT(col)` counts non-NULLs. `COUNT(DISTINCT col)` counts distinct non-NULLs.",
      "`WHERE` filters rows before grouping; `HAVING` filters groups after.",
      "Any non-aggregated column in the SELECT list must appear in `GROUP BY` (strict mode enforces this).",
      "`GROUP BY` collapses rows; `PARTITION BY` does not.",
      "Aggregate the many-side FIRST, then join, or your sums will be multiplied by the join fan-out."
    ]}
  ]
},
{
  key:"sqltemplates", name:"SQL Query Templates", side:"sql",
  tagline:"The eight query shapes that cover most interview questions.",
  blocks:[
    {t:"code",title:"Top-N per group",lang:"sql",lines:[
      "WITH ranked AS (",
      "  SELECT e.*,",
      "         DENSE_RANK() OVER (PARTITION BY dept_id ORDER BY salary DESC) AS rk",
      "  FROM employee e",
      ")",
      "SELECT dept_id, name, salary",
      "FROM ranked",
      "WHERE rk <= 3;",
      "",
      "-- DENSE_RANK includes ties. Use ROW_NUMBER for exactly N rows,",
      "-- RANK if you want gaps after ties."
    ]},
    {t:"code",title:"Anti-join, three ways",lang:"sql",lines:[
      "-- 1. NOT EXISTS  (null-safe, usually the best plan)",
      "SELECT c.* FROM customer c",
      "WHERE NOT EXISTS (SELECT 1 FROM orders o WHERE o.cust_id = c.id);",
      "",
      "-- 2. LEFT JOIN ... IS NULL",
      "SELECT c.* FROM customer c",
      "LEFT JOIN orders o ON o.cust_id = c.id",
      "WHERE o.id IS NULL;",
      "",
      "-- 3. EXCEPT  (whole-row set difference)",
      "SELECT id FROM customer",
      "EXCEPT",
      "SELECT cust_id FROM orders;",
      "",
      "-- NEVER: NOT IN (SELECT cust_id FROM orders) -- one NULL kills the whole result"
    ]},
    {t:"code",title:"Aggregate before joining (avoids fan-out)",lang:"sql",lines:[
      "-- WRONG: joining two one-to-many tables multiplies rows and doubles the sums",
      "-- RIGHT: collapse each side to one row per key first",
      "WITH order_totals AS (",
      "  SELECT cust_id, SUM(amount) AS order_amt FROM orders GROUP BY cust_id",
      "), refund_totals AS (",
      "  SELECT cust_id, SUM(amount) AS refund_amt FROM refunds GROUP BY cust_id",
      ")",
      "SELECT c.id, c.name,",
      "       COALESCE(o.order_amt, 0) - COALESCE(r.refund_amt, 0) AS net",
      "FROM customer c",
      "LEFT JOIN order_totals  o ON o.cust_id = c.id",
      "LEFT JOIN refund_totals r ON r.cust_id = c.id;"
    ]},
    {t:"code",title:"Conditional aggregation (pivot)",lang:"sql",lines:[
      "SELECT store_id,",
      "       SUM(CASE WHEN status = 'paid'     THEN amount ELSE 0 END) AS paid,",
      "       SUM(CASE WHEN status = 'refunded' THEN amount ELSE 0 END) AS refunded,",
      "       COUNT(CASE WHEN status = 'failed' THEN 1 END)             AS failed_count,",
      "       ROUND(AVG(CASE WHEN status = 'paid' THEN 1.0 ELSE 0 END), 3) AS paid_rate",
      "FROM payments",
      "GROUP BY store_id;",
      "",
      "-- COUNT(CASE WHEN c THEN 1 END)         -> counts only matches   (correct)",
      "-- COUNT(CASE WHEN c THEN 1 ELSE 0 END)  -> counts every row       (wrong)"
    ]},
    {t:"code",title:"Running total and moving average",lang:"sql",lines:[
      "SELECT day, store_id, revenue,",
      "       SUM(revenue) OVER (PARTITION BY store_id ORDER BY day",
      "                          ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running_total,",
      "       AVG(revenue) OVER (PARTITION BY store_id ORDER BY day",
      "                          ROWS BETWEEN 6 PRECEDING AND CURRENT ROW)          AS ma7,",
      "       revenue - LAG(revenue) OVER (PARTITION BY store_id ORDER BY day)      AS dod_change",
      "FROM daily_revenue;",
      "",
      "-- Always spell out ROWS. The default RANGE frame lumps tied ORDER BY values together."
    ]},
    {t:"code",title:"Gaps and islands — longest consecutive streak",lang:"sql",lines:[
      "WITH numbered AS (",
      "  SELECT user_id, login_date,",
      "         ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY login_date) AS rn",
      "  FROM (SELECT DISTINCT user_id, login_date FROM logins) d",
      "), grouped AS (",
      "  SELECT user_id, login_date,",
      "         login_date - CAST(rn AS INT) AS island_key   -- runs share this key",
      "  FROM numbered",
      ")",
      "SELECT user_id, COUNT(*) AS streak_len,",
      "       MIN(login_date) AS streak_start, MAX(login_date) AS streak_end",
      "FROM grouped",
      "GROUP BY user_id, island_key",
      "ORDER BY streak_len DESC;"
    ]},
    {t:"code",title:"Deduplicate keeping one row per key",lang:"sql",lines:[
      "WITH ranked AS (",
      "  SELECT id, email,",
      "         ROW_NUMBER() OVER (PARTITION BY email ORDER BY created_at, id) AS rn",
      "  FROM person",
      ")",
      "DELETE FROM person",
      "WHERE id IN (SELECT id FROM ranked WHERE rn > 1);",
      "",
      "-- The trailing id in ORDER BY makes the tie-break deterministic."
    ]},
    {t:"code",title:"Recursive CTE — walk a hierarchy",lang:"sql",lines:[
      "WITH RECURSIVE org AS (",
      "  SELECT id, name, manager_id, 1 AS depth        -- anchor",
      "  FROM employee",
      "  WHERE id = :root_id",
      "  UNION ALL",
      "  SELECT e.id, e.name, e.manager_id, o.depth + 1 -- recursive member",
      "  FROM employee e",
      "  JOIN org o ON e.manager_id = o.id",
      "  WHERE o.depth < 20                             -- terminating guard",
      ")",
      "SELECT * FROM org ORDER BY depth, name;"
    ]},
    {t:"code",title:"Cohort retention (day 1 and day 7)",lang:"sql",lines:[
      "WITH first_day AS (",
      "  SELECT user_id, MIN(activity_date) AS d0 FROM activity GROUP BY user_id",
      ")",
      "SELECT f.d0 AS cohort,",
      "       COUNT(DISTINCT f.user_id) AS cohort_size,",
      "       COUNT(DISTINCT CASE WHEN a.activity_date = f.d0 + 1 THEN a.user_id END) AS d1,",
      "       COUNT(DISTINCT CASE WHEN a.activity_date = f.d0 + 7 THEN a.user_id END) AS d7",
      "FROM first_day f",
      "LEFT JOIN activity a ON a.user_id = f.user_id",
      "GROUP BY f.d0",
      "ORDER BY cohort;"
    ]}
  ]
},
{
  key:"dbmsref", name:"DBMS Viva Sheet", side:"sql",
  tagline:"Isolation, normal forms, indexes — compact answers that score.",
  blocks:[
    {t:"h",text:"Isolation levels versus anomalies"},
    {t:"table",
     head:["Level","Dirty read","Non-repeatable read","Phantom read"],
     rows:[
      ["READ UNCOMMITTED","Possible","Possible","Possible"],
      ["READ COMMITTED","Prevented","Possible","Possible"],
      ["REPEATABLE READ","Prevented","Prevented","Possible (prevented in InnoDB via gap locks)"],
      ["SERIALIZABLE","Prevented","Prevented","Prevented"]
     ]},
    {t:"list",items:[
      "Postgres and Oracle default to READ COMMITTED; MySQL InnoDB defaults to REPEATABLE READ.",
      "Dirty read = you saw uncommitted data. Non-repeatable = the SAME ROW changed. Phantom = NEW ROWS appeared.",
      "Isolation does not automatically stop lost updates — that needs `SELECT ... FOR UPDATE` or a version check."
    ]},
    {t:"h",text:"Normal forms"},
    {t:"table",
     head:["Form","Requirement","Anomaly removed"],
     rows:[
      ["1NF","Atomic values, no repeating groups","Cannot query or index inside a packed field"],
      ["2NF","1NF + no partial dependency on part of a composite key","Update anomaly on duplicated partial-key facts"],
      ["3NF","2NF + no transitive dependency between non-key attributes","Deleting a row destroys an unrelated fact"],
      ["BCNF","Every determinant is a superkey","Residual redundancy with overlapping candidate keys"],
      ["4NF","No multi-valued dependency","Cartesian blow-up of independent multi-valued facts"]
     ]},
    {t:"h",text:"Index decision guide"},
    {t:"table",
     head:["Situation","Do this","Because"],
     rows:[
      ["Frequent equality filter on one column","Single-column B-tree index","Direct seek instead of a scan"],
      ["Filter on A then sort by B","Composite index `(A, B)`","Serves both the seek and the ordering"],
      ["Query selects only indexed columns","Add them as included columns","Covering index avoids the table lookup"],
      ["Predicate wraps the column in a function","Rewrite the predicate, or add a functional index","Otherwise it is non-sargable"],
      ["`LIKE '%term'`","Full-text or trigram index","A leading wildcard cannot use a B-tree"],
      ["Low-selectivity column (e.g. boolean)","Usually no index","A scan is cheaper than random I/O"],
      ["Write-heavy table","Fewer indexes","Every index is maintained on every write"],
      ["Range or ORDER BY queries","B-tree, not hash","Hash indexes have no ordering"]
     ]},
    {t:"h",text:"Answers worth rehearsing verbatim"},
    {t:"list",items:[
      "ACID — Atomicity (all or nothing), Consistency (constraints preserved), Isolation (concurrent transactions do not observe partial state), Durability (committed work survives a crash, via the write-ahead log).",
      "Clustered index defines physical row order, so one per table and the leaf level IS the data; non-clustered is a separate structure whose leaves point back to the row.",
      "Sharding splits data across machines; partitioning splits it within one database; replication copies it for read scale and failover.",
      "SQL injection is fixed by parameterised queries — never by escaping or blocklists.",
      "Denormalization trades write complexity and anomaly risk for read speed; it belongs in analytical, read-heavy systems."
    ]}
  ]
},
{
  key:"protocol", name:"The 45-Minute Round", side:"dsa",
  tagline:"How to run the interview, not just solve the problem.",
  blocks:[
    {t:"p",text:"Most rejections are not because the candidate could not solve it. They are because of silence, an unstated assumption, or code written before the approach was agreed."},
    {t:"h",text:"Minute-by-minute"},
    {t:"table",
     head:["Time","Do","Say something like"],
     rows:[
      ["0–3","Restate the problem and confirm the input and output types","'So I am given an unsorted array of integers, possibly with duplicates, and I return the indices — is that right?'"],
      ["3–5","Ask about constraints and edge cases BEFORE thinking","'How large can n be? Can values be negative? Is the input guaranteed non-empty? Is there exactly one answer?'"],
      ["5–8","State the brute force and its complexity, then say why it is not enough","'The obvious approach is O(n^2). Given n up to 10^5 that is too slow, so I want O(n log n) or better.'"],
      ["8–13","Propose the real approach and get agreement before writing anything","'I think a hash map of value to index gets this to one pass. Shall I code that?'"],
      ["13–30","Code it, narrating decisions rather than syntax","'I am seeding the map with zero so subarrays starting at index 0 are counted.'"],
      ["30–38","Dry-run on a small example out loud, then on an edge case","'Let me trace [3, 3] with target 6 — i=0 stores 3, i=1 finds it. Good.'"],
      ["38–42","State final complexity, both time and space, and any trade-off","'O(n) time, O(n) space. I could get O(1) space by sorting, but then I lose the original indices.'"],
      ["42–45","Ask a real question about the team or the work","—"]
     ]},
    {t:"h",text:"Say these out loud — they are graded"},
    {t:"list",items:[
      "Name the pattern the moment you recognise it: 'this is a monotonic stack problem'.",
      "Name the edge cases you are handling, even the ones that do not apply.",
      "State the complexity BEFORE you are asked. Every time.",
      "When stuck, narrate the stall: 'the issue is that the window is not monotone because of the negatives, so let me switch to prefix sums.'",
      "When you spot your own bug mid-code, say so and fix it — that reads as rigour, not weakness.",
      "Distinguish auxiliary space from output space explicitly."
    ]},
    {t:"h",text:"Never do these"},
    {t:"list",items:[
      "Start coding before the interviewer has agreed to the approach.",
      "Go silent for more than about 20 seconds — think out loud instead.",
      "Say 'I have seen this one' and recite a solution without deriving it.",
      "Claim a complexity you have not checked.",
      "Argue when corrected. Take the hint, say thank you, and use it — hints are part of the rubric."
    ]},
    {t:"h",text:"When you are genuinely stuck"},
    {t:"list",items:[
      "Solve a smaller version: n = 1, n = 2, or the array all-positive.",
      "Solve a related easier problem and then ask what breaks.",
      "Write the brute force, get it correct, then optimise it in front of them — a correct slow answer beats an incorrect fast one.",
      "Ask directly: 'I am considering a heap and a sort here — do you have a preference on which direction I explore?'"
    ]}
  ]
}
];